#!/bin/bash
onion compile \
    --lib src \
    --lib vendor/corneltek/cliframework/src \
    --lib vendor/corneltek/getoptionkit/src \
    --lib vendor/corneltek/universal/src \
    --lib vendor/twig/twig/lib \
    --classloader \
    --bootstrap scripts/genphp.embed \
    --executable \
    --output genphp.phar
mv -v genphp.phar genphp
chmod +x genphp
