#!/usr/bin/env php
<?php
require 'vendor/pear/Universal/ClassLoader/BasePathClassLoader.php';
$loader = new Universal\ClassLoader\BasePathClassLoader(array( 'vendor/pear' , 'src' ));
$loader->register();

$app = new GenPHP\Application;
$app->run( $argv );
