#!/usr/bin/env php
<?php
require 'vendor/pear/Universal/ClassLoader/BasePathClassLoader.php';
$loader = new Universal\ClassLoader\BasePathClassLoader(array( 'vendor/pear' , 'src' ));
$loader->register();

try {
    $app = new GenPHP\Application;
    $app->run( $argv );
} catch( Exception $e ) {

}
